#include "pins.h"
#include "digio.h"
#include <avr/io.h>

const Pin pins[] =
  {
    //0
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=0,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //1
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=1,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //2
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=2,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //3
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=3,
      .tcc_register=&TCCR2A,
      .oc_register=&OCR2B,
      .com_mask=(1<<COM2B0)|(1<<COM2B1)
    },
    //4
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=5,
      .tcc_register=0, 
      .oc_register=0,
      .com_mask=0
    },
    //5
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=5,
      .tcc_register=&TCCR0A,
      .oc_register=&OCR0B,
      .com_mask=(1<<COM0B0)|(1<<COM0B1)
    },
    //6
    {
      .in_register=&PIND,
      .out_register=&PORTD,
      .dir_register=&DDRD,
      .bit=6,
      .tcc_register=&TCCR0A,
      .oc_register=&OCR0A,
      .com_mask=(1<<COM0A0)|(1<<COM0A1)
    },
    //7
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=7,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //8
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=0,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //9
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=1,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //10
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=2,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //11
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=3,
      .tcc_register=&TCCR2A,
      .oc_register=&OCR2A,
      .com_mask=(1<<COM2A0)|(1<<COM2A1)
    },
    //12
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=4,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    },
    //13
    {
      .in_register=&PINB,
      .out_register=&PORTB,
      .dir_register=&DDRB,
      .bit=5,
      .tcc_register=0,
      .oc_register=0,
      .com_mask=0
    }
  };
